FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json ./
COPY apps/api/package.json apps/api/package.json
COPY packages/db/package.json packages/db/package.json
COPY packages/shared/package.json packages/shared/package.json
RUN npm ci
COPY . .
RUN npm run db:generate -w packages/db && npm run build -w packages/shared && npm run build -w packages/db && npm run build -w apps/api
CMD ["npm", "run", "start", "-w", "apps/api"]
