FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json ./
COPY apps/web/package.json apps/web/package.json
RUN npm ci
COPY . .
ARG NEXT_PUBLIC_API_URL=http://localhost:4000
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
# ARG NEXT_PUBLIC_ENABLE_ASSISTANT=true
# ENV NEXT_PUBLIC_ENABLE_ASSISTANT=$NEXT_PUBLIC_ENABLE_ASSISTANT
RUN npm run build -w apps/web
CMD ["npm", "run", "start", "-w", "apps/web"]
